### ISSUE TITLE
Error when executing `mix deps.audit` if git isn't installed

### ISSUE THREAD

**Issue by dmarcoux** [mirego/mix_audit#18]
Salut!

I attempted to execute `mix deps.audit` in a development environment which didn't have `git` installed and I got this somewhat cryptic error:

```
** (ErlangError) Erlang error: :enoent
    (elixir 1.14.0) lib/system.ex:1053: System.cmd("git", ["clone", "--quiet", "https://github.com/mirego/elixir-security-advisories.git", "/home/dany/.local/share/elixir-security-advisories-mirego"], [])
    lib/mix_audit/repo.ex:5: MixAudit.Repo.advisories/0
    lib/mix_audit/cli/audit.ex:11: MixAudit.CLI.Audit.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

I was a bit confused at first, but I realized that `git` was missing. It's completely fine that `git` is a hard dependency to fetch the Elixir security advisories, but its presence should not be implied. Perhaps a note in the README about this would be nice, right now there is this sentence:

> A list of security advisories fetched from the GitHub-sourced elixir-security-advisories repository

To take this potential issue into account, the code could also be adapted to handle [errors from `System.cmd/3`](https://hexdocs.pm/elixir/1.14/System.html#cmd/3-error-reasons).

What do you think?

**Comment by remi** [comment]
Salut Dany!

You’re right, I based the implementation on [bundler-audit](https://github.com/rubysec/bundler-audit)’s [`Bundler::Audit::Database.download`](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/database.rb#L117-L133). The gem also [lists `git`](https://github.com/rubysec/bundler-audit#requirements) as a requirement.

I’ll add better error handling and a requirement section in `README.md` 🙂
