### ISSUE TITLE
Error after upgrading to Elixir 1.15.0

### ISSUE THREAD

**Issue by Toady00** [mirego/mix_audit#22]
It was working before on Elixir 1.14.x, but after upgrading to 1.15.0 I get:

```
$ mix deps.audit
** (ArgumentError) argument error
    (mix_audit 2.1.0) lib/mix_audit/repo.ex:27: MixAudit.Repo.synchronize/0
    (mix_audit 2.1.0) lib/mix_audit/repo.ex:5: MixAudit.Repo.advisories/0
    (mix_audit 2.1.0) lib/mix_audit/cli/audit.ex:11: MixAudit.CLI.Audit.run/1
    (mix 1.15.0) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.0) lib/mix/cli.ex:92: Mix.CLI.run_task/2
Error: exit status 1
```

**Comment by remi** [comment]
`lib/mix_audit/repo.ex:27` is this line: https://github.com/mirego/mix_audit/blob/main/lib/mix_audit/repo.ex#L27

So it looks like there’s an error while performing Git operations (and the error handling is not working properly, `reraise` has no `message` option 😐).

I don’t see the link with Elixir 1.14 vs 1.15 though 🤔

**Comment by Toady00** [comment]
yeah I looked at your source for a moment and nothing jumped out at me but I'm also about to start a meeting in 2 minutes. It was just a hunch that it was 1.15 🤷 since it was working and now it's not. I definitely gave git installed and verified in that same bash session it was available and on path. Not that I think it's related but it's git version 2.41.0.

**Comment by remi** [comment]
I just merged #23 to make the error message more explicit. I’ll release a new version.

**Comment by remi** [comment]
@Toady00 Can you test it again with `mix_audit` 2.1.1?

**Comment by remi** [comment]
I see your `$HOME` variable is `/root` — are you running the script as `root`? Are you sure `git` is available for _the user running the Erlang process_?

The `git clone` command be able to clone even in a directory that doesn’t exist so it doesn’t look like the error is related to the path.

For example if I run: 

```
> System.cmd("git", ["clone", "--quiet", "https://github.com/mirego/elixir-security-advisories.git", "foo/bar/baz/does/not/exist"])
```

it works fine. However if I run

```
> System.cmd("nogit", ["clone", "--quiet", "https://github.com/mirego/elixir-security-advisories.git", "foo/bar/baz/does/not/exist"])
** (ErlangError) Erlang error: :enoent
    (elixir 1.15.0) lib/system.ex:1092: System.cmd("nogit", ["clone", "--quiet", "https://github.com/mirego/elixir-security-advisories.git", "foo/bar/baz/does/not/exist"], [])
```

I get the same `Erlang error: :enoent` error as you. So it definitely looks like the `"git"` part in `System.cmd("git", …)` is throwing the error 😖

**Comment by Toady00** [comment]
I'm sorry, you're right and I've wasted your time. I'm not sure how this was working before, but this isn't on the mix_audit at all. The way I've setup my dev environment, I don't have elixir or erlang installed at all. I have a shell script that runs all mix and iex commands in a docker container and I use direnv to setup the path to those scripts and to mount project directory into the container and a whole host of other things. That's why it appears I'm running as root, cause technically I'm not super worried about security in the container I'm running locally for my own development that only lives for a few seconds at a time. But I also don't have git installed in the image I'm using, it's installed natively on my system. So I sometimes forget that while I can run:

```
$ mix hex.info
Hex:    2.0.6
Elixir: 1.15.2
OTP:    26.0.2

Built with: Elixir 1.14.2 and OTP 23.3
$ git --version
git version 2.41.0
```

and they both look like they are running natively, the mix command isn't running natively. It is in a container.

Having said all that, is there any appetite for removing the dependency on git? I could see doing something like creating a release in the `elixir-security-advisories` repo as part of the github action, and then you could use the unauthenticated API call to fetch the release as a zip and unzip it locally. The fetching and unziping can be done natively in elixir and remove the system dependencies. I could potentially work on some PRs to do that if there was an appetite for it.

Either way, I'm going to close this issue as this was completely on me. I'm still not sure how it ever worked but 🤷
