### ISSUE TITLE
Feature Request: Easier to understand output when there is no fixed version

### ISSUE THREAD

**Issue by axelson** [mirego/mix_audit#5]
Currently if a dependency has a vulnerability but doesn't have a fixed version the output could be more explicit about that. For example this is what it currently looks like for sweet_xml:
```
Name: sweet_xml
Version: 0.6.6
Lockfile: /Users/jason/dev/my_app/mix.lock
CVE: 2019-15160
URL: https://github.com/kbrw/sweet_xml/issues/71
Title: Inline DTD allows XML bomb attack
Patched versions:

Vulnerabilities found!
```

Instead of `Patched versions:`, maybe it should say `Patched versions: NONE` or something.

**Comment by remi** [comment]
Hi Jason,

Thank you for the suggestion. I applied it in #6.

Cheers!

**Comment by remi** [comment]
`mix_audit` v0.1.4 has now been published with this change if you want to try it.

**Comment by axelson** [comment]
Looks great! Thanks :)
